### ISSUE TITLE
work progress

### ISSUE THREAD

**Issue by inlife** [Gurkenschreck/Gurkenplayer#3]
Hey there!

I discovered your mod, a few days ago. Yeah, almost year from initial commit :D
It didn't start (many game api updates, etc.), but it's pretty amazing. 

Anyways, i have a question, why have you stopped developing ?

Thank you!

**Comment by Override92** [comment]
Hi,

I also think it would be great to build a City in coop-mode.
I would be happy if this project is going to be continued.

//Override

**Comment by Mitgenosse** [comment]
Hello Inlife and Override92,
I mainly stopped because I needed some in-depth knowledge of the unity engine so I picked up unity and slowly drifted away until I forgot about this.
Yeah, coop cities skylines sounds very tempting, but I am currently working (in my opinion) on a more interesting project atm. 
Greetings

**Comment by inlife** [comment]
Thank you for response!

Im thinking over creating fork and continuing your work.
You made pretty solid base. :smile:

Thank you!

**Comment by Override92** [comment]
That'd be great Inlife! I would love to support you but I don't have the needed knowledge for that.

//Override

**Comment by Mitgenosse** [comment]
Great, that would be nice. Tell me how it works out for you :+1:
